//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insolvency.Integration.Models {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Insolvency.Integration.Models.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname should be less than 100 characters.
        /// </summary>
        public static string Api_Surname_Length_Validation {
            get {
                return ResourceManager.GetString("Api_Surname_Length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter surname.
        /// </summary>
        public static string Api_Surname_Required_Validation {
            get {
                return ResourceManager.GetString("Api_Surname_Required_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breathing Space reference number should be less than 100 characters.
        /// </summary>
        public static string Bs_Ref_Length_Validation {
            get {
                return ResourceManager.GetString("Bs_Ref_Length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Breathing Space reference number.
        /// </summary>
        public static string Bs_Ref_Required_Validation {
            get {
                return ResourceManager.GetString("Bs_Ref_Required_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day must be between 1 and 31.
        /// </summary>
        public static string DoB_Day_Range_Validation {
            get {
                return ResourceManager.GetString("DoB_Day_Range_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s date of birth must include a day.
        /// </summary>
        public static string DoB_Day_Required_Validation {
            get {
                return ResourceManager.GetString("DoB_Day_Required_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month must be between 1 and 12.
        /// </summary>
        public static string DoB_Month_Range_Validation {
            get {
                return ResourceManager.GetString("DoB_Month_Range_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s date of birth must include a month.
        /// </summary>
        public static string DoB_Month_Required_Validation {
            get {
                return ResourceManager.GetString("DoB_Month_Required_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year must be between 1880 and 2004.
        /// </summary>
        public static string DoB_Year_Range_Validation {
            get {
                return ResourceManager.GetString("DoB_Year_Range_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s date of birth must include a year.
        /// </summary>
        public static string DoB_Year_Required_Validation {
            get {
                return ResourceManager.GetString("DoB_Year_Required_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s first name should be less than 100 characters.
        /// </summary>
        public static string FName_Length_Validation {
            get {
                return ResourceManager.GetString("FName_Length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter client&apos;s first name.
        /// </summary>
        public static string FName_Required_Validation {
            get {
                return ResourceManager.GetString("FName_Required_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s last name should be less than 100 characters.
        /// </summary>
        public static string LName_Length_Validation {
            get {
                return ResourceManager.GetString("LName_Length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter client&apos;s last name.
        /// </summary>
        public static string LName_Required_Validation {
            get {
                return ResourceManager.GetString("LName_Required_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s middle name should be less than 100 characters.
        /// </summary>
        public static string MName_Length_Validation {
            get {
                return ResourceManager.GetString("MName_Length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account&apos;s reference number should be less than 100 characters.
        /// </summary>
        public static string Ref_Length_Validation {
            get {
                return ResourceManager.GetString("Ref_Length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter reference number.
        /// </summary>
        public static string Ref_Required_Validation {
            get {
                return ResourceManager.GetString("Ref_Required_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name should be less than 100 characters.
        /// </summary>
        public static string Surname_Length_Validation {
            get {
                return ResourceManager.GetString("Surname_Length_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter last name.
        /// </summary>
        public static string Surname_Required_Validation {
            get {
                return ResourceManager.GetString("Surname_Required_Validation", resourceCulture);
            }
        }
    }
}
