using System;

namespace Insolvency.Integration.Gateways.Entities
{
    public class inss_moneyadviserorganisation : IDynamicsEntity
    {
        public Guid? inss_moneyadviserorganisationid { get; set; }
        public string inss_name { get; set; }

        public Guid GetId() => inss_moneyadviserorganisationid.Value;

        //        _owningteam_value:[Edm.Guid Nullable=True]
        //        inss_onboardeddate:[Edm.DateTimeOffset Nullable=True Precision=0]
        //        importsequencenumber:[Edm.Int32 Nullable=True]
        //        _modifiedby_value:[Edm.Guid Nullable=True]
        //        _modifiedonbehalfby_value:[Edm.Guid Nullable=True]
        //        statuscode:[Edm.Int32 Nullable=True]
        //        versionnumber:[Edm.Int64 Nullable=True]
        //        inss_fcaexemption:[Edm.Boolean Nullable=True]
        //        _inss_fcaaccreditedorganisationid_value:[Edm.Guid Nullable=True]
        //        inss_englandwalesregistered:[Edm.Boolean Nullable=True]
        //        overriddencreatedon:[Edm.DateTimeOffset Nullable=True Precision=0]
        //        inss_emailaddress:[Edm.String Nullable=True Unicode=False]
        //        _ownerid_value:[Edm.Guid Nullable=True]
        //        inss_faxnumber:[Edm.String Nullable=True Unicode=False]
        //        inss_companyregistrationnumber:[Edm.String Nullable=True Unicode=False]
        //        statecode:[Edm.Int32 Nullable=True]
        //        createdon:[Edm.DateTimeOffset Nullable=True Precision=0]
        //        _inss_tradingbrand_value:[Edm.Guid Nullable=True]
        //        timezoneruleversionnumber:[Edm.Int32 Nullable=True]
        //        _owningbusinessunit_value:[Edm.Guid Nullable=True]
        //        modifiedon:[Edm.DateTimeOffset Nullable=True Precision=0]
        //        _createdby_value:[Edm.Guid Nullable=True]
        //        inss_telephonenumber:[Edm.String Nullable=True Unicode=False]
        //        _owninguser_value:[Edm.Guid Nullable=True]
        //        _createdonbehalfby_value:[Edm.Guid Nullable=True]
        //        utcconversiontimezonecode:[Edm.Int32 Nullable=True]
        //        createdby:[Microsoft.Dynamics.CRM.systemuser Nullable=False]
        //        createdonbehalfby:[Microsoft.Dynamics.CRM.systemuser Nullable=False]
        //        modifiedby:[Microsoft.Dynamics.CRM.systemuser Nullable=False]
        //        modifiedonbehalfby:[Microsoft.Dynamics.CRM.systemuser Nullable=False]
        //        owninguser:[Microsoft.Dynamics.CRM.systemuser Nullable=False]
        //        owningteam:[Microsoft.Dynamics.CRM.team Nullable=False]
        //        ownerid:[Microsoft.Dynamics.CRM.principal Nullable=False]
        //        owningbusinessunit:[Microsoft.Dynamics.CRM.businessunit Nullable=False]
        //        inss_moneyadviserorganisation_ActivityPointers:[Collection([Microsoft.Dynamics.CRM.activitypointer Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_msfp_surveyinvites:[Collection([Microsoft.Dynamics.CRM.msfp_surveyinvite Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_msfp_surveyresponses:[Collection([Microsoft.Dynamics.CRM.msfp_surveyresponse Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_ntt_notificationemails:[Collection([Microsoft.Dynamics.CRM.ntt_notificationemail Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_ntt_notificationletters:[Collection([Microsoft.Dynamics.CRM.ntt_notificationletter Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_SyncErrors:[Collection([Microsoft.Dynamics.CRM.syncerror Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_AsyncOperations:[Collection([Microsoft.Dynamics.CRM.asyncoperation Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_MailboxTrackingFolders:[Collection([Microsoft.Dynamics.CRM.mailboxtrackingfolder Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_ProcessSession:[Collection([Microsoft.Dynamics.CRM.processsession Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_BulkDeleteFailures:[Collection([Microsoft.Dynamics.CRM.bulkdeletefailure Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_PrincipalObjectAttributeAccesses:[Collection([Microsoft.Dynamics.CRM.principalobjectattributeaccess Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_Appointments:[Collection([Microsoft.Dynamics.CRM.appointment Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_Emails:[Collection([Microsoft.Dynamics.CRM.email Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_Faxes:[Collection([Microsoft.Dynamics.CRM.fax Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_Letters:[Collection([Microsoft.Dynamics.CRM.letter Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_PhoneCalls:[Collection([Microsoft.Dynamics.CRM.phonecall Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_Tasks:[Collection([Microsoft.Dynamics.CRM.task Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_RecurringAppointmentMasters:[Collection([Microsoft.Dynamics.CRM.recurringappointmentmaster Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_SocialActivities:[Collection([Microsoft.Dynamics.CRM.socialactivity Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_Annotations:[Collection([Microsoft.Dynamics.CRM.annotation Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_ServiceAppointments:[Collection([Microsoft.Dynamics.CRM.serviceappointment Nullable=False]) Nullable=True]
        //ntt_moneyadviserorganisation_ntt_breathingspacemoratorium_ManagingMoneyAdviserOrganisationId:[Collection([Microsoft.Dynamics.CRM.ntt_breathingspacemoratorium Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_ntt_notificationapis:[Collection([Microsoft.Dynamics.CRM.ntt_notificationapi Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_msfp_alerts:[Collection([Microsoft.Dynamics.CRM.msfp_alert Nullable=False]) Nullable=True]
        //inss_FCAAccreditedOrganisationId:[Microsoft.Dynamics.CRM.inss_fcaaccreditedorganisation Nullable=False]
        //inss_TradingBrand:[Microsoft.Dynamics.CRM.inss_tradingbrand Nullable=False]
        //inss_moneyadviserorganisation_inss_inssaddress_MoneyAdviserOrganisationId:[Collection([Microsoft.Dynamics.CRM.inss_inssaddress Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_inss_moneyadvise:[Collection([Microsoft.Dynamics.CRM.inss_moneyadviserbusinesscontact Nullable=False]) Nullable=True]
        //inss_moneyadviserorganisation_inss_tradingbrand_MoneyAdviserOrganisationId:[Collection([Microsoft.Dynamics.CRM.inss_tradingbrand Nullable=False]) Nullable=True]
        //ntt_customaudit_MoneyAdviserOrganisationI:[Collection([Microsoft.Dynamics.CRM.ntt_customaudit Nullable=False]) Nullable=True]
    }
}
