using System;

namespace Insolvency.Integration.Gateways.Entities
{
    public class Ntt_breathingspacetype
    {
        public Guid? ntt_breathingspacetypeid { get; set; }
        public string ntt_name { get; set; }
        public int statecode { get; set; }
        public int statuscode { get; set; }
        //_createdby_value:[Edm.Guid Nullable=True]
        //_ownerid_value:[Edm.Guid Nullable=True]
        //ntt_retentionperiodstartdate:[Edm.DateTimeOffset Nullable=True Precision=0]
        //ntt_mhtreatmentenddate:[Edm.DateTimeOffset Nullable=True Precision=0]
        //ntt_commencementdate:[Edm.DateTimeOffset Nullable=True Precision=0]
        //ntt_createdbymoneyadvisername:[Edm.String Nullable=True Unicode=False]
        //_modifiedonbehalfby_value:[Edm.Guid Nullable=True]
        //_createdonbehalfby_value:[Edm.Guid Nullable=True]
        //ntt_lastupdatedbymoneyadvisername:[Edm.String Nullable=True Unicode=False]
        //ntt_triggerpointofcontactsubmitnotification:[Edm.Boolean Nullable=True]
        //timezoneruleversionnumber:[Edm.Int32 Nullable=True]
        //ntt_removedfromregisterdate:[Edm.DateTimeOffset Nullable=True Precision=0]
        //ntt_activeregister:[Edm.Boolean Nullable=True]
        //_owningbusinessunit_value:[Edm.Guid Nullable=True]
        //_owninguser_value:[Edm.Guid Nullable=True]
        //utcconversiontimezonecode:[Edm.Int32 Nullable=True]
        //ntt_closuredate:[Edm.DateTimeOffset Nullable=True Precision=0]
        //ntt_activeregisterperiodenddate:[Edm.DateTimeOffset Nullable=True Precision=0]
        //ntt_submissiondate:[Edm.DateTimeOffset Nullable=True Precision=0]
        //ntt_moneyadviserreference:[Edm.String Nullable=True Unicode=False]
        //_modifiedby_value:[Edm.Guid Nullable=True]
        //_ntt_debtorid_value:[Edm.Guid Nullable=True]
        //importsequencenumber:[Edm.Int32 Nullable=True]
        // ntt_retentionperiodenddate:[Edm.DateTimeOffset Nullable=True Precision=0]
        // ntt_activeregisterperiodstartdate:[Edm.DateTimeOffset Nullable=True Precision=0]
        //_owningteam_value:[Edm.Guid Nullable=True]
        //ntt_createdbymoneyadviserorganisation:[Edm.String Nullable=True Unicode=False]
        //versionnumber:[Edm.Int64 Nullable=True]
        // ntt_expirydate:[Edm.DateTimeOffset Nullable=True Precision=0]
        // createdon:[Edm.DateTimeOffset Nullable=True Precision=0]
        // ntt_lastupdatedbymoneyadviserdate:[Edm.DateTimeOffset Nullable=True Precision=0]
        // modifiedon:[Edm.DateTimeOffset Nullable=True Precision=0]        //        
        //_ntt_managingmoneyadviserorganisationid_value:[Edm.Guid Nullable=True]
        //        overriddencreatedon:[Edm.DateTimeOffset Nullable=True Precision=0]
        //        createdby:[Microsoft.Dynamics.CRM.systemuser Nullable=False]
        //        createdonbehalfby:[Microsoft.Dynamics.CRM.systemuser Nullable=False]
        //        modifiedby:[Microsoft.Dynamics.CRM.systemuser Nullable=False]
        //        modifiedonbehalfby:[Microsoft.Dynamics.CRM.systemuser Nullable=False]
        //        owninguser:[Microsoft.Dynamics.CRM.systemuser Nullable=False]
        //        owningteam:[Microsoft.Dynamics.CRM.team Nullable=False]
        //        ownerid:[Microsoft.Dynamics.CRM.principal Nullable=False]
        //        owningbusinessunit:[Microsoft.Dynamics.CRM.businessunit Nullable=False]
        //        ntt_breathingspacemoratorium_ActivityPointers:[Collection([Microsoft.Dynamics.CRM.activitypointer Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_msfp_surveyinvites:[Collection([Microsoft.Dynamics.CRM.msfp_surveyinvite Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_msfp_surveyresponses:[Collection([Microsoft.Dynamics.CRM.msfp_surveyresponse Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_SyncErrors:[Collection([Microsoft.Dynamics.CRM.syncerror Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_AsyncOperations:[Collection([Microsoft.Dynamics.CRM.asyncoperation Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_MailboxTrackingFolders:[Collection([Microsoft.Dynamics.CRM.mailboxtrackingfolder Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_ProcessSession:[Collection([Microsoft.Dynamics.CRM.processsession Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_BulkDeleteFailures:[Collection([Microsoft.Dynamics.CRM.bulkdeletefailure Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_PrincipalObjectAttributeAccesses:[Collection([Microsoft.Dynamics.CRM.principalobjectattributeaccess Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_Appointments:[Collection([Microsoft.Dynamics.CRM.appointment Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_Emails:[Collection([Microsoft.Dynamics.CRM.email Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_Faxes:[Collection([Microsoft.Dynamics.CRM.fax Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_Letters:[Collection([Microsoft.Dynamics.CRM.letter Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_PhoneCalls:[Collection([Microsoft.Dynamics.CRM.phonecall Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_Tasks:[Collection([Microsoft.Dynamics.CRM.task Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_RecurringAppointmentMasters:[Collection([Microsoft.Dynamics.CRM.recurringappointmentmaster Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_SocialActivities:[Collection([Microsoft.Dynamics.CRM.socialactivity Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_Annotations:[Collection([Microsoft.Dynamics.CRM.annotation Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_ServiceAppointments:[Collection([Microsoft.Dynamics.CRM.serviceappointment Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_ntt_notificationemails:[Collection([Microsoft.Dynamics.CRM.ntt_notificationemail Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_ntt_notificationletters:[Collection([Microsoft.Dynamics.CRM.ntt_notificationletter Nullable=False]) Nullable=True]
        //ntt_debtorid:[Microsoft.Dynamics.CRM.ntt_breathingspacedebtor Nullable=False]
        //        ntt_breathingspacemoratorium_ntt_breathingspacedebt_BreathingSpaceMoratoriumId:[Collection([Microsoft.Dynamics.CRM.ntt_breathingspacedebt Nullable=False]) Nullable=True]
        //ntt_breathingspacemoratorium_ntt_contactrole_BreathingSpaceMoratoriumid:[Collection([Microsoft.Dynamics.CRM.ntt_contactrole Nullable=False]) Nullable=True]
        //ntt_breathingspacestatusid:[Microsoft.Dynamics.CRM.ntt_breathingspacestatustype Nullable=False]
        //        ntt_breathingspacetypeid:[Microsoft.Dynamics.CRM.ntt_breathingspacetype Nullable=False]
        //        ntt_ManagingMoneyAdviserOrganisationId:[Microsoft.Dynamics.CRM.inss_moneyadviserorganisation Nullable=False]
        //        ntt_breathingspacemoratorium_ntt_notificationapis:[Collection([Microsoft.Dynamics.CRM.ntt_notificationapi Nullable=False]) Nullable=True]

    }
}