namespace Insolvency.Integration.Gateways.Entities
{
    public class ntt_moneyadviserorganisationtask
    {
        public Ntt_breathingspacemoratorium ntt_BreathingSpaceMoratoriumId_ntt_moneyadviserorganisationtask { get; set; }
        public ntt_debteligibilityreview regardingobjectid_ntt_debteligibilityreview_ntt_moneyadviserorganisationtask { get; set; }


        //        importsequencenumber:[Edm.Int32 Nullable=True]
        //        _ntt_moneyadviserorganisationid_value:[Edm.Guid Nullable=True]
        //        _ntt_breathingspacemoratoriumid_value:[Edm.Guid Nullable=True]
        //        ntt_action:[Edm.Int32 Nullable=True]
        //        _ntt_debteligibilityreviewtypeid_value:[Edm.Guid Nullable=True]
        //        overriddencreatedon:[Edm.DateTimeOffset Nullable=True Precision=0]
        //        _ntt_creditororganisationid_value:[Edm.Guid Nullable=True]
        //        regardingobjectid_ntt_breathingspaceadhoccreditor_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.ntt_breathingspaceadhoccreditor Nullable=False]
        //        regardingobjectid_ntt_breathingspacedebtor_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.ntt_breathingspacedebtor Nullable=False]
        //        regardingobjectid_ntt_breathingspacemoratorium_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.ntt_breathingspacemoratorium Nullable=False]
        //        regardingobjectid_ntt_externalcontact_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.ntt_externalcontact Nullable=False]
        //        regardingobjectid_inss_cmpcreditor_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.inss_cmpcreditor Nullable=False]
        //        regardingobjectid_inss_creditorbusinesscontact_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.inss_creditorbusinesscontact Nullable=False]
        //        regardingobjectid_inss_moneyadviserbusinesscontact_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.inss_moneyadviserbusinesscontact Nullable=False]
        //        regardingobjectid_inss_moneyadviserorganisation_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.inss_moneyadviserorganisation Nullable=False]
        //        regardingobjectid_ntt_breathingspacedebt_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.ntt_breathingspacedebt Nullable=False]
        //        regardingobjectid_ntt_debtoreligibilityreview_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.ntt_debtoreligibilityreview Nullable=False]
        //        regardingobjectid_lead_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.lead Nullable=False]
        //        regardingobjectid_bookableresourcebooking_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.bookableresourcebooking Nullable=False]
        //        regardingobjectid_bookableresourcebookingheader_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.bookableresourcebookingheader Nullable=False]
        //        regardingobjectid_bulkoperation_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.bulkoperation Nullable=False]
        //        regardingobjectid_campaign_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.campaign Nullable=False]
        //        regardingobjectid_campaignactivity_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.campaignactivity Nullable=False]
        //        regardingobjectid_contract_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.contract Nullable=False]
        //        regardingobjectid_entitlement_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.entitlement Nullable=False]
        //        regardingobjectid_entitlementtemplate_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.entitlementtemplate Nullable=False]
        //        regardingobjectid_incident_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.incident Nullable=False]
        //        regardingobjectid_site_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.site Nullable=False]
        //        serviceid_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.service Nullable=False]
        //        regardingobjectid_msdyn_customerasset_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.msdyn_customerasset Nullable=False]
        //        regardingobjectid_msdyn_playbookinstance_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.msdyn_playbookinstance Nullable=False]
        //        regardingobjectid_invoice_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.invoice Nullable=False]
        //        regardingobjectid_opportunity_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.opportunity Nullable=False]
        //        regardingobjectid_quote_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.quote Nullable=False]
        //        regardingobjectid_salesorder_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.salesorder Nullable=False]
        //        regardingobjectid_msdyn_postalbum_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.msdyn_postalbum Nullable=False]
        //        regardingobjectid_new_interactionforemail_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.interactionforemail Nullable=False]
        //        regardingobjectid_knowledgebaserecord_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.knowledgebaserecord Nullable=False]
        //        regardingobjectid_account_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.account Nullable=False]
        //        createdby_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.systemuser Nullable=False]
        //        regardingobjectid_contact_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.contact Nullable=False]
        //        sendermailboxid_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.mailbox Nullable=False]
        //        transactioncurrencyid_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.transactioncurrency Nullable=False]
        //        ownerid_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.principal Nullable=False]
        //        owninguser_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.systemuser Nullable=False]
        //        sla_activitypointer_sla_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.sla Nullable=False]
        //        owningbusinessunit_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.businessunit Nullable=False]
        //        regardingobjectid_knowledgearticle_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.knowledgearticle Nullable=False]
        //        modifiedonbehalfby_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.systemuser Nullable=False]
        //        createdonbehalfby_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.systemuser Nullable=False]
        //        modifiedby_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.systemuser Nullable=False]
        //        owningteam_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.team Nullable=False]
        //        slainvokedid_activitypointer_sla_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.sla Nullable=False]
        //        activityid_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.activitypointer Nullable=False]
        //        ntt_moneyadviserorganisationtask_activity_parties:[Collection([Microsoft.Dynamics.CRM.activityparty Nullable=False]) Nullable=True]
        //CampaignResponse_ntt_moneyadviserorganisationtasks:[Collection([Microsoft.Dynamics.CRM.campaignresponse Nullable=False]) Nullable=True]
        //ntt_moneyadviserorganisationtask_ActionCards:[Collection([Microsoft.Dynamics.CRM.actioncard Nullable=False]) Nullable=True]
        //ntt_moneyadviserorganisationtask_SyncErrors:[Collection([Microsoft.Dynamics.CRM.syncerror Nullable=False]) Nullable=True]
        //ntt_moneyadviserorganisationtask_AsyncOperations:[Collection([Microsoft.Dynamics.CRM.asyncoperation Nullable=False]) Nullable=True]
        //ntt_moneyadviserorganisationtask_MailboxTrackingFolders:[Collection([Microsoft.Dynamics.CRM.mailboxtrackingfolder Nullable=False]) Nullable=True]
        //ntt_moneyadviserorganisationtask_ProcessSession:[Collection([Microsoft.Dynamics.CRM.processsession Nullable=False]) Nullable=True]
        //ntt_moneyadviserorganisationtask_BulkDeleteFailures:[Collection([Microsoft.Dynamics.CRM.bulkdeletefailure Nullable=False]) Nullable=True]
        //ntt_moneyadviserorganisationtask_PrincipalObjectAttributeAccesses:[Collection([Microsoft.Dynamics.CRM.principalobjectattributeaccess Nullable=False]) Nullable=True]
        //ntt_moneyadviserorganisationtask_connections1:[Collection([Microsoft.Dynamics.CRM.connection Nullable=False]) Nullable=True]
        //ntt_moneyadviserorganisationtask_connections2:[Collection([Microsoft.Dynamics.CRM.connection Nullable=False]) Nullable=True]
        //ntt_moneyadviserorganisationtask_QueueItems:[Collection([Microsoft.Dynamics.CRM.queueitem Nullable=False]) Nullable=True]
        //ntt_moneyadviserorganisationtask_Annotations:[Collection([Microsoft.Dynamics.CRM.annotation Nullable=False]) Nullable=True]
        //ntt_moneyadviserorganisationtask_Feedback:[Collection([Microsoft.Dynamics.CRM.feedback Nullable=False]) Nullable=True]
        //ntt_MoneyAdviserOrganisationId_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.inss_moneyadviserorganisation Nullable=False]
        //        ntt_CreditorOrganisationId_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.ntt_breathingspacecreditor Nullable=False]
        //        ntt_DebtEligibilityReviewTypeId_ntt_moneyadviserorganisationtask:[Microsoft.Dynamics.CRM.ntt_debteligibilityreviewtype Nullable=False]
    }
}